version: "3.9"

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    ports:
      - "80:8080"
    volumes:
      - ./config:/etc/chirpstack
    command: ["chirpstack", "--config", "/etc/chirpstack"]
    depends_on:
      - redis
      - mosquitto
    restart: always

  redis:
    image: redis:7
    restart: always

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always