version: "3.9"

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    ports:
      - "8080:8080"  # Puerto web
    environment:
      - DSN=${POSTGRES_DSN}
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7
    restart: always