version: "3.9"

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    ports:
      - "80:8080"  # Expone puerto 8080 del contenedor en el puerto 80 externo
    environment:
      - DSN=${POSTGRES_DSN}
      - REDIS_URL=redis://redis:6379
      - MQTT_BROKER=ssl://mosquitto:8883
    depends_on:
      - redis
      - mosquitto
    restart: always

  redis:
    image: redis:7
    restart: always

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always                                                 